source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.7"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-seo-tag"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-feed"
end

# Windows não suporta alguns gems
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance
gem "wdm", ">= 0.1.0", :platforms => [:mingw, :x64_mingw, :mswin]

# Debug
gem "jekyll-include-cache"

