source "https://rubygems.org"

# Jekyll para desenvolvimento local
gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.7"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end

# Windows não suporta alguns gems
platforms :windows do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "wdm", ">= 0.1.0"
end

# Debug
gem "jekyll-include-cache"

